core:
  - changed-files:
    - any-glob-to-any-file: "src/**"

ci:
  - changed-files:
    - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.md"

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - "Cargo.toml"
      - "Cargo.lock"

security:
  - changed-files:
    - any-glob-to-any-file:
      - "SECURITY.md"
      - "src/sys/auth.rs"
      - "src/limits/**"
